server:
  port: 8182

spring:
  flyway:
    user: sa
    password: password
    url: jdbc:h2:mem:buyer-bank-db
    locations: classpath:db/migration
  datasource:
    url: jdbc:h2:mem:buyer-bank-db
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none

service:
  test: fasdfa
  banks:
    - bankId: seller_bank
      url: ${SELLER_BANK_URL:http://10.224.8.54:8888/api/v1/notification}
