DB_URL: jdbc:mysql://localhost:3306/reasunta?useSSL=false&serverTimezone=UTC
DB_USERNAME: root
DB_PASSWORD: pass123
DB_DRIVER: com.mysql.cj.jdbc.Driver

server:
  port: 8182

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: ${DB_DRIVER}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties.hibernate.default_schema: ${DB_SCHEMA}

service:
  banks:
    - bankId: seller_bank
      url: ${SELLER_BANK_URL:http://10.224.8.54:8888/api/v1/notification}