server:
  port: 8182

spring:
  config:
    activate:
      on-profile: local
  h2:
    console:
      # for debug reasons
      enabled: true
#  jpa:
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true

#logging:
#  level:
#    org:
#      hibernate:
#        type: trace
